version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive
    - bodyclose
    - noctx
    - sqlclosecheck
    - unconvert
    - unparam
  settings:
    revive:
      rules:
        - name: error-strings
    gosec:
      excludes:
        - G404

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/SalehMWS/Muse

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
