// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditLog = `-- name: AppendAuditLog :exec
INSERT INTO audit_logs (
    id, user_id, action, result, resource_type, resource_id,
    ip_address, user_agent, request_id, correlation_id, trace_id, metadata, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type AppendAuditLogParams struct {
	ID            uuid.UUID          `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Action        string             `json:"action"`
	Result        string             `json:"result"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    string             `json:"resource_id"`
	IpAddress     string             `json:"ip_address"`
	UserAgent     string             `json:"user_agent"`
	RequestID     string             `json:"request_id"`
	CorrelationID string             `json:"correlation_id"`
	TraceID       string             `json:"trace_id"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AppendAuditLog(ctx context.Context, arg AppendAuditLogParams) error {
	_, err := q.db.Exec(ctx, appendAuditLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.Result,
		arg.ResourceType,
		arg.ResourceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.CorrelationID,
		arg.TraceID,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const listAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, user_id, action, result, resource_type, resource_id, ip_address, user_agent, request_id, correlation_id, trace_id, metadata, created_at FROM audit_logs
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAuditLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Result,
			&i.ResourceType,
			&i.ResourceID,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.CorrelationID,
			&i.TraceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
