// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contents.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContent = `-- name: CreateContent :one
INSERT INTO contents (id, user_id, title, caption, status, language, content_type, visibility, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, title, caption, status, language, content_type, visibility, tags, published_at, created_at, updated_at, deleted_at
`

type CreateContentParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Title       string    `json:"title"`
	Caption     string    `json:"caption"`
	Status      string    `json:"status"`
	Language    string    `json:"language"`
	ContentType string    `json:"content_type"`
	Visibility  string    `json:"visibility"`
	Tags        []string  `json:"tags"`
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, createContent,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Caption,
		arg.Status,
		arg.Language,
		arg.ContentType,
		arg.Visibility,
		arg.Tags,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Caption,
		&i.Status,
		&i.Language,
		&i.ContentType,
		&i.Visibility,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContentByIDForUser = `-- name: GetContentByIDForUser :one
SELECT id, user_id, title, caption, status, language, content_type, visibility, tags, published_at, created_at, updated_at, deleted_at FROM contents WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL LIMIT 1
`

type GetContentByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetContentByIDForUser(ctx context.Context, arg GetContentByIDForUserParams) (Content, error) {
	row := q.db.QueryRow(ctx, getContentByIDForUser, arg.ID, arg.UserID)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Caption,
		&i.Status,
		&i.Language,
		&i.ContentType,
		&i.Visibility,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listContents = `-- name: ListContents :many
SELECT id, user_id, title, caption, status, language, content_type, visibility, tags, published_at, created_at, updated_at, deleted_at FROM contents
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR language = $3)
  AND ($4::text IS NULL OR content_type = $4)
  AND ($5::text IS NULL OR $5 = ANY (tags))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListContentsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Status      *string   `json:"status"`
	Language    *string   `json:"language"`
	ContentType *string   `json:"content_type"`
	Tag         *string   `json:"tag"`
	Lim         int32     `json:"lim"`
}

func (q *Queries) ListContents(ctx context.Context, arg ListContentsParams) ([]Content, error) {
	rows, err := q.db.Query(ctx, listContents,
		arg.UserID,
		arg.Status,
		arg.Language,
		arg.ContentType,
		arg.Tag,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Content{}
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Caption,
			&i.Status,
			&i.Language,
			&i.ContentType,
			&i.Visibility,
			&i.Tags,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentsAfter = `-- name: ListContentsAfter :many
SELECT id, user_id, title, caption, status, language, content_type, visibility, tags, published_at, created_at, updated_at, deleted_at FROM contents
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR language = $3)
  AND ($4::text IS NULL OR content_type = $4)
  AND ($5::text IS NULL OR $5 = ANY (tags))
  AND (
    created_at < $6
    OR (created_at = $6 AND id < $7)
  )
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListContentsAfterParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	Status          *string            `json:"status"`
	Language        *string            `json:"language"`
	ContentType     *string            `json:"content_type"`
	Tag             *string            `json:"tag"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
	Lim             int32              `json:"lim"`
}

func (q *Queries) ListContentsAfter(ctx context.Context, arg ListContentsAfterParams) ([]Content, error) {
	rows, err := q.db.Query(ctx, listContentsAfter,
		arg.UserID,
		arg.Status,
		arg.Language,
		arg.ContentType,
		arg.Tag,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Content{}
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Caption,
			&i.Status,
			&i.Language,
			&i.ContentType,
			&i.Visibility,
			&i.Tags,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContent = `-- name: UpdateContent :one
UPDATE contents
SET title = $3,
    caption = $4,
    status = $5,
    language = $6,
    content_type = $7,
    visibility = $8,
    tags = $9,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, title, caption, status, language, content_type, visibility, tags, published_at, created_at, updated_at, deleted_at
`

type UpdateContentParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Title       string    `json:"title"`
	Caption     string    `json:"caption"`
	Status      string    `json:"status"`
	Language    string    `json:"language"`
	ContentType string    `json:"content_type"`
	Visibility  string    `json:"visibility"`
	Tags        []string  `json:"tags"`
}

func (q *Queries) UpdateContent(ctx context.Context, arg UpdateContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, updateContent,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Caption,
		arg.Status,
		arg.Language,
		arg.ContentType,
		arg.Visibility,
		arg.Tags,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Caption,
		&i.Status,
		&i.Language,
		&i.ContentType,
		&i.Visibility,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
