// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, user_id, title, source, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, source, status, chunk_count, last_error, created_at, updated_at
`

type CreateDocumentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Source string    `json:"source"`
	Status string    `json:"status"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Source,
		arg.Status,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Source,
		&i.Status,
		&i.ChunkCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocumentForUser = `-- name: DeleteDocumentForUser :exec
DELETE FROM documents WHERE id = $1 AND user_id = $2
`

type DeleteDocumentForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDocumentForUser(ctx context.Context, arg DeleteDocumentForUserParams) error {
	_, err := q.db.Exec(ctx, deleteDocumentForUser, arg.ID, arg.UserID)
	return err
}

const getDocumentByIDForUser = `-- name: GetDocumentByIDForUser :one
SELECT id, user_id, title, source, status, chunk_count, last_error, created_at, updated_at FROM documents WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetDocumentByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetDocumentByIDForUser(ctx context.Context, arg GetDocumentByIDForUserParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByIDForUser, arg.ID, arg.UserID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Source,
		&i.Status,
		&i.ChunkCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsByUser = `-- name: ListDocumentsByUser :many
SELECT id, user_id, title, source, status, chunk_count, last_error, created_at, updated_at FROM documents WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByUser(ctx context.Context, userID uuid.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Source,
			&i.Status,
			&i.ChunkCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE documents
SET status = $2, chunk_count = $3, last_error = $4, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, source, status, chunk_count, last_error, created_at, updated_at
`

type UpdateDocumentStatusParams struct {
	ID         uuid.UUID `json:"id"`
	Status     string    `json:"status"`
	ChunkCount int32     `json:"chunk_count"`
	LastError  *string   `json:"last_error"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentStatus,
		arg.ID,
		arg.Status,
		arg.ChunkCount,
		arg.LastError,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Source,
		&i.Status,
		&i.ChunkCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
