// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instagram_accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInstagramAccountForUser = `-- name: DeleteInstagramAccountForUser :exec
DELETE FROM instagram_accounts WHERE id = $1 AND user_id = $2
`

type DeleteInstagramAccountForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteInstagramAccountForUser(ctx context.Context, arg DeleteInstagramAccountForUserParams) error {
	_, err := q.db.Exec(ctx, deleteInstagramAccountForUser, arg.ID, arg.UserID)
	return err
}

const getInstagramAccountByIDForUser = `-- name: GetInstagramAccountByIDForUser :one
SELECT id, user_id, instagram_user_id, username, account_type, access_token, token_expires_at, scopes, status, connected_at, last_refreshed_at, created_at, updated_at FROM instagram_accounts WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetInstagramAccountByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetInstagramAccountByIDForUser(ctx context.Context, arg GetInstagramAccountByIDForUserParams) (InstagramAccount, error) {
	row := q.db.QueryRow(ctx, getInstagramAccountByIDForUser, arg.ID, arg.UserID)
	var i InstagramAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstagramUserID,
		&i.Username,
		&i.AccountType,
		&i.AccessToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.Status,
		&i.ConnectedAt,
		&i.LastRefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstagramAccountsByUser = `-- name: ListInstagramAccountsByUser :many
SELECT id, user_id, instagram_user_id, username, account_type, access_token, token_expires_at, scopes, status, connected_at, last_refreshed_at, created_at, updated_at FROM instagram_accounts WHERE user_id = $1 ORDER BY connected_at DESC
`

func (q *Queries) ListInstagramAccountsByUser(ctx context.Context, userID uuid.UUID) ([]InstagramAccount, error) {
	rows, err := q.db.Query(ctx, listInstagramAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstagramAccount{}
	for rows.Next() {
		var i InstagramAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstagramUserID,
			&i.Username,
			&i.AccountType,
			&i.AccessToken,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.Status,
			&i.ConnectedAt,
			&i.LastRefreshedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstagramAccountToken = `-- name: UpdateInstagramAccountToken :one
UPDATE instagram_accounts
SET access_token = $2,
    token_expires_at = $3,
    status = $4,
    last_refreshed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, instagram_user_id, username, account_type, access_token, token_expires_at, scopes, status, connected_at, last_refreshed_at, created_at, updated_at
`

type UpdateInstagramAccountTokenParams struct {
	ID             uuid.UUID          `json:"id"`
	AccessToken    string             `json:"access_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	Status         string             `json:"status"`
}

func (q *Queries) UpdateInstagramAccountToken(ctx context.Context, arg UpdateInstagramAccountTokenParams) (InstagramAccount, error) {
	row := q.db.QueryRow(ctx, updateInstagramAccountToken,
		arg.ID,
		arg.AccessToken,
		arg.TokenExpiresAt,
		arg.Status,
	)
	var i InstagramAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstagramUserID,
		&i.Username,
		&i.AccountType,
		&i.AccessToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.Status,
		&i.ConnectedAt,
		&i.LastRefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInstagramAccount = `-- name: UpsertInstagramAccount :one
INSERT INTO instagram_accounts (
    id, user_id, instagram_user_id, username, account_type,
    access_token, token_expires_at, scopes, status, connected_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (user_id, instagram_user_id) DO UPDATE
SET username = EXCLUDED.username,
    account_type = EXCLUDED.account_type,
    access_token = EXCLUDED.access_token,
    token_expires_at = EXCLUDED.token_expires_at,
    scopes = EXCLUDED.scopes,
    status = EXCLUDED.status,
    connected_at = now(),
    last_refreshed_at = NULL,
    updated_at = now()
RETURNING id, user_id, instagram_user_id, username, account_type, access_token, token_expires_at, scopes, status, connected_at, last_refreshed_at, created_at, updated_at
`

type UpsertInstagramAccountParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	InstagramUserID string             `json:"instagram_user_id"`
	Username        string             `json:"username"`
	AccountType     *string            `json:"account_type"`
	AccessToken     string             `json:"access_token"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	Scopes          *string            `json:"scopes"`
	Status          string             `json:"status"`
}

func (q *Queries) UpsertInstagramAccount(ctx context.Context, arg UpsertInstagramAccountParams) (InstagramAccount, error) {
	row := q.db.QueryRow(ctx, upsertInstagramAccount,
		arg.ID,
		arg.UserID,
		arg.InstagramUserID,
		arg.Username,
		arg.AccountType,
		arg.AccessToken,
		arg.TokenExpiresAt,
		arg.Scopes,
		arg.Status,
	)
	var i InstagramAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstagramUserID,
		&i.Username,
		&i.AccountType,
		&i.AccessToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.Status,
		&i.ConnectedAt,
		&i.LastRefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
