// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (id, content_id, url, media_type, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, content_id, url, media_type, position, created_at
`

type CreateMediaParams struct {
	ID        uuid.UUID `json:"id"`
	ContentID uuid.UUID `json:"content_id"`
	Url       string    `json:"url"`
	MediaType string    `json:"media_type"`
	Position  int32     `json:"position"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.ID,
		arg.ContentID,
		arg.Url,
		arg.MediaType,
		arg.Position,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Url,
		&i.MediaType,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMediaForContent = `-- name: DeleteMediaForContent :exec
DELETE FROM media WHERE id = $1 AND content_id = $2
`

type DeleteMediaForContentParams struct {
	ID        uuid.UUID `json:"id"`
	ContentID uuid.UUID `json:"content_id"`
}

func (q *Queries) DeleteMediaForContent(ctx context.Context, arg DeleteMediaForContentParams) error {
	_, err := q.db.Exec(ctx, deleteMediaForContent, arg.ID, arg.ContentID)
	return err
}

const getMediaByIDForContent = `-- name: GetMediaByIDForContent :one
SELECT id, content_id, url, media_type, position, created_at FROM media WHERE id = $1 AND content_id = $2 LIMIT 1
`

type GetMediaByIDForContentParams struct {
	ID        uuid.UUID `json:"id"`
	ContentID uuid.UUID `json:"content_id"`
}

func (q *Queries) GetMediaByIDForContent(ctx context.Context, arg GetMediaByIDForContentParams) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByIDForContent, arg.ID, arg.ContentID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Url,
		&i.MediaType,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaByContent = `-- name: ListMediaByContent :many
SELECT id, content_id, url, media_type, position, created_at FROM media WHERE content_id = $1 ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListMediaByContent(ctx context.Context, contentID uuid.UUID) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByContent, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.Url,
			&i.MediaType,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
