// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Content struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Title       string             `json:"title"`
	Caption     string             `json:"caption"`
	Status      string             `json:"status"`
	Language    string             `json:"language"`
	ContentType string             `json:"content_type"`
	Visibility  string             `json:"visibility"`
	Tags        []string           `json:"tags"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type InstagramAccount struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	InstagramUserID string             `json:"instagram_user_id"`
	Username        string             `json:"username"`
	AccountType     *string            `json:"account_type"`
	AccessToken     string             `json:"access_token"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	Scopes          *string            `json:"scopes"`
	Status          string             `json:"status"`
	ConnectedAt     pgtype.Timestamptz `json:"connected_at"`
	LastRefreshedAt pgtype.Timestamptz `json:"last_refreshed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Medium struct {
	ID        uuid.UUID          `json:"id"`
	ContentID uuid.UUID          `json:"content_id"`
	Url       string             `json:"url"`
	MediaType string             `json:"media_type"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Publication struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	ContentID          uuid.UUID          `json:"content_id"`
	InstagramAccountID uuid.UUID          `json:"instagram_account_id"`
	Platform           string             `json:"platform"`
	PlatformPostID     *string            `json:"platform_post_id"`
	Status             string             `json:"status"`
	Permalink          *string            `json:"permalink"`
	ResponseJson       []byte             `json:"response_json"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Schedule struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	ContentID          uuid.UUID          `json:"content_id"`
	InstagramAccountID uuid.UUID          `json:"instagram_account_id"`
	ScheduledFor       pgtype.Timestamptz `json:"scheduled_for"`
	Timezone           string             `json:"timezone"`
	CronExpression     *string            `json:"cron_expression"`
	MediaType          *string            `json:"media_type"`
	Status             string             `json:"status"`
	RetryCount         int32              `json:"retry_count"`
	MaxRetries         int32              `json:"max_retries"`
	NextRetryAt        pgtype.Timestamptz `json:"next_retry_at"`
	LastError          *string            `json:"last_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	Device           *string            `json:"device"`
	IpAddress        *string            `json:"ip_address"`
	UserAgent        *string            `json:"user_agent"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastActivityAt   pgtype.Timestamptz `json:"last_activity_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     *string            `json:"avatar_url"`
	Status        string             `json:"status"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
