// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPublication = `-- name: CreatePublication :one
INSERT INTO publications (
    id, user_id, content_id, instagram_account_id, platform,
    platform_post_id, status, permalink, response_json, published_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, content_id, instagram_account_id, platform, platform_post_id, status, permalink, response_json, published_at, created_at, updated_at
`

type CreatePublicationParams struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	ContentID          uuid.UUID          `json:"content_id"`
	InstagramAccountID uuid.UUID          `json:"instagram_account_id"`
	Platform           string             `json:"platform"`
	PlatformPostID     *string            `json:"platform_post_id"`
	Status             string             `json:"status"`
	Permalink          *string            `json:"permalink"`
	ResponseJson       []byte             `json:"response_json"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreatePublication(ctx context.Context, arg CreatePublicationParams) (Publication, error) {
	row := q.db.QueryRow(ctx, createPublication,
		arg.ID,
		arg.UserID,
		arg.ContentID,
		arg.InstagramAccountID,
		arg.Platform,
		arg.PlatformPostID,
		arg.Status,
		arg.Permalink,
		arg.ResponseJson,
		arg.PublishedAt,
	)
	var i Publication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentID,
		&i.InstagramAccountID,
		&i.Platform,
		&i.PlatformPostID,
		&i.Status,
		&i.Permalink,
		&i.ResponseJson,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicationsByContentForUser = `-- name: ListPublicationsByContentForUser :many
SELECT id, user_id, content_id, instagram_account_id, platform, platform_post_id, status, permalink, response_json, published_at, created_at, updated_at FROM publications
WHERE content_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ListPublicationsByContentForUserParams struct {
	ContentID uuid.UUID `json:"content_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ListPublicationsByContentForUser(ctx context.Context, arg ListPublicationsByContentForUserParams) ([]Publication, error) {
	rows, err := q.db.Query(ctx, listPublicationsByContentForUser, arg.ContentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Publication{}
	for rows.Next() {
		var i Publication
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContentID,
			&i.InstagramAccountID,
			&i.Platform,
			&i.PlatformPostID,
			&i.Status,
			&i.Permalink,
			&i.ResponseJson,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
