// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSchedule = `-- name: CancelSchedule :exec
UPDATE schedules SET status = 'cancelled', updated_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'scheduled'
`

type CancelScheduleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CancelSchedule(ctx context.Context, arg CancelScheduleParams) error {
	_, err := q.db.Exec(ctx, cancelSchedule, arg.ID, arg.UserID)
	return err
}

const claimDueSchedules = `-- name: ClaimDueSchedules :many
UPDATE schedules
SET status = 'publishing', updated_at = now()
WHERE id IN (
    SELECT s.id FROM schedules s
    WHERE s.status = 'scheduled' AND s.scheduled_for <= $1
    ORDER BY s.scheduled_for
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, user_id, content_id, instagram_account_id, scheduled_for, timezone, cron_expression, media_type, status, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
`

type ClaimDueSchedulesParams struct {
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) ClaimDueSchedules(ctx context.Context, arg ClaimDueSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, claimDueSchedules, arg.ScheduledFor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContentID,
			&i.InstagramAccountID,
			&i.ScheduledFor,
			&i.Timezone,
			&i.CronExpression,
			&i.MediaType,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
    id, user_id, content_id, instagram_account_id, scheduled_for,
    timezone, cron_expression, media_type, max_retries
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, content_id, instagram_account_id, scheduled_for, timezone, cron_expression, media_type, status, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at
`

type CreateScheduleParams struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	ContentID          uuid.UUID          `json:"content_id"`
	InstagramAccountID uuid.UUID          `json:"instagram_account_id"`
	ScheduledFor       pgtype.Timestamptz `json:"scheduled_for"`
	Timezone           string             `json:"timezone"`
	CronExpression     *string            `json:"cron_expression"`
	MediaType          *string            `json:"media_type"`
	MaxRetries         int32              `json:"max_retries"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.ID,
		arg.UserID,
		arg.ContentID,
		arg.InstagramAccountID,
		arg.ScheduledFor,
		arg.Timezone,
		arg.CronExpression,
		arg.MediaType,
		arg.MaxRetries,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentID,
		&i.InstagramAccountID,
		&i.ScheduledFor,
		&i.Timezone,
		&i.CronExpression,
		&i.MediaType,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleByIDForUser = `-- name: GetScheduleByIDForUser :one
SELECT id, user_id, content_id, instagram_account_id, scheduled_for, timezone, cron_expression, media_type, status, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at FROM schedules WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetScheduleByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetScheduleByIDForUser(ctx context.Context, arg GetScheduleByIDForUserParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByIDForUser, arg.ID, arg.UserID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentID,
		&i.InstagramAccountID,
		&i.ScheduledFor,
		&i.Timezone,
		&i.CronExpression,
		&i.MediaType,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedulesByContentForUser = `-- name: ListSchedulesByContentForUser :many
SELECT id, user_id, content_id, instagram_account_id, scheduled_for, timezone, cron_expression, media_type, status, retry_count, max_retries, next_retry_at, last_error, created_at, updated_at FROM schedules
WHERE content_id = $1 AND user_id = $2
ORDER BY scheduled_for DESC
`

type ListSchedulesByContentForUserParams struct {
	ContentID uuid.UUID `json:"content_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ListSchedulesByContentForUser(ctx context.Context, arg ListSchedulesByContentForUserParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByContentForUser, arg.ContentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContentID,
			&i.InstagramAccountID,
			&i.ScheduledFor,
			&i.Timezone,
			&i.CronExpression,
			&i.MediaType,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduleFailed = `-- name: MarkScheduleFailed :exec
UPDATE schedules SET status = 'failed', last_error = $2, updated_at = now()
WHERE id = $1
`

type MarkScheduleFailedParams struct {
	ID        uuid.UUID `json:"id"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) MarkScheduleFailed(ctx context.Context, arg MarkScheduleFailedParams) error {
	_, err := q.db.Exec(ctx, markScheduleFailed, arg.ID, arg.LastError)
	return err
}

const markScheduleQueued = `-- name: MarkScheduleQueued :exec
UPDATE schedules SET status = 'queued', last_error = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkScheduleQueued(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markScheduleQueued, id)
	return err
}

const rescheduleSchedule = `-- name: RescheduleSchedule :exec
UPDATE schedules
SET status = 'scheduled', scheduled_for = $2, retry_count = 0, next_retry_at = NULL, last_error = NULL, updated_at = now()
WHERE id = $1
`

type RescheduleScheduleParams struct {
	ID           uuid.UUID          `json:"id"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
}

func (q *Queries) RescheduleSchedule(ctx context.Context, arg RescheduleScheduleParams) error {
	_, err := q.db.Exec(ctx, rescheduleSchedule, arg.ID, arg.ScheduledFor)
	return err
}

const retrySchedule = `-- name: RetrySchedule :exec
UPDATE schedules
SET status = 'scheduled', retry_count = $2, scheduled_for = $3, next_retry_at = $3, last_error = $4, updated_at = now()
WHERE id = $1
`

type RetryScheduleParams struct {
	ID           uuid.UUID          `json:"id"`
	RetryCount   int32              `json:"retry_count"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	LastError    *string            `json:"last_error"`
}

func (q *Queries) RetrySchedule(ctx context.Context, arg RetryScheduleParams) error {
	_, err := q.db.Exec(ctx, retrySchedule,
		arg.ID,
		arg.RetryCount,
		arg.ScheduledFor,
		arg.LastError,
	)
	return err
}
